### ISSUE TITLE
"error in docker-compose up" when creating a --wp --letsencrypt site

### ISSUE THREAD

**Issue by nelscon538** [EasyEngine/site-type-wp#221]
Hi,
i keep getting this error when making a website with --wp --letsencrypt

Apologies if this post lacks more info. Please advise.

OS:
Ubuntu 22.04.4 LTS x86_64

Kind regards

![afbeelding](https://github.com/EasyEngine/site-type-wp/assets/94167157/b6a023fc-81a8-49c7-98d0-c90b03c60dce)
![Unssssstitled-1](https://github.com/EasyEngine/site-type-wp/assets/94167157/ceb05fa3-28bd-4c6d-ae5e-8be3ebe14e42)

**Comment by dlackty** [comment]
This is due to docker-compose v1 compatibility issue. You can downgrade docker-ce to 5:25.0.5-1 as a workaround.

**Comment by pagaling** [comment]
> downgrade docker-ce to 5:25.0.5-1

Not very familiar with Docker. Can you help with steps or link on how to downgrade? Thanks

**Comment by olefm-dev** [comment]
Hi! Experiencing the same issue - and I'm aware that a downgrade of Docker is a current workaround. Is there however an ETA on when this will be solved? Thanks in advance <3

**Comment by L0RD-ZER0** [comment]
Support for Docker Compose v2 has been added in latest releases of EasyEngine. You can check out further details for the release at our [Release v4.7.0 Blogpost](https://easyengine.io/blog/easyengine-v4-7-0-released/). This issue is resolved in this update.

Please update EasyEngine to the latest version using ``ee cli update`` command.  In order for a fresh installation instead, consider using the command ``wget -qO ee rt.cx/ee4 && sudo bash ee`` to use the automated installation script to install the latest version of EasyEngine.
